[package]
name = "proc_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
paste = "1.0"
common = { path = "../common" }

[lib]
proc-macro = true

